# Corrected docker-compose.yml for Raspberry Pi
name: immich

services:
    immich-server:
        container_name: immich_server
        image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
        cpus: "3.0"
        # Memory limit set to 4GB
        mem_limit: 4g
        # Granting access to the Pi's video hardware for acceleration
        devices:
            - /dev/dri:/dev/dri
        volumes:
            - ${UPLOAD_LOCATION}:/data
            - /etc/localtime:/etc/localtime:ro

        env_file:
            - .env
        ports:
            - "2283:2283"
        depends_on:
            - redis
            - database
        restart: always
        healthcheck:
            disable: false

    immich-machine-learning:
        container_name: immich_machine_learning
        image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
        cpus: "1.0"
        # Memory limit set to 2GB
        mem_limit: 2g
        volumes:
            - model-cache:/cache
        env_file:
            - .env
        restart: always
        healthcheck:
            disable: false

    redis:
        container_name: immich_redis
        image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
        # Memory limit set to 256MB
        mem_limit: 256m
        healthcheck:
            test: redis-cli ping || exit 1
        restart: always

    database:
        container_name: immich_postgres
        image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:41eacbe83eca995561fe43814fd4891e16e39632806253848efaf04d3c8a8b84
        # Memory limit set to 1GB
        mem_limit: 1g
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE_NAME}
            POSTGRES_INITDB_ARGS: "--data-checksums"
        volumes:
            - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
        shm_size: 128mb
        restart: always

volumes:
    model-cache:
