version: '3.8'

services:
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    ports:
      - "61208:61208"  # Web server port
      - "61209:61209"  # RESTful API port (optional)
    environment:
      - TZ=${TZ:-Europe/Paris}  # Use your timezone
      - GLANCES_OPT=-w  # Web server mode
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    network_mode: host  # Required for proper system monitoring

