- Media:
    - Jellyfin:
        icon: jellyfin
        href: http://100.69.22.42:8096
        description: Serveur média
    - Immich:
        icon: immich
        href: http://100.69.22.42:2283
        description: Photos

- Productivité:
    - Budget Vacances:
        icon: google-sheets
        href: http://100.69.22.42:8501
        description: Prorata & Dépenses
    - File Browser:
        icon: https://filebrowserquantum.com/logo.svg
        href: http://100.69.22.42:8095/
        description: Drive
    - Actual:
        icon: http://100.69.22.42:3000/icons/actual.png
        href: https://plougastel.tailb3be33.ts.net:444/
        description: Finances
    - Vikunja:
        icon: https://vikunja.io/favicon.svg
        href: http://100.69.22.42:3456
        description: To Do app

- Infra:
    - Portainer:
        icon: portainer
        href: https://100.69.22.42:9443/
        description: Système
    - Cockpit:
        icon: https://raw.githubusercontent.com/cockpit-project/cockpit/main/src/branding/default/logo.svg
        href: https://plougastel.tailb3be33.ts.net:9090/
        description: Admin & Terminal
    - Syncthing:
        icon: https://raw.githubusercontent.com/syncthing/syncthing/refs/heads/main/assets/logo.ico
        href: http://100.69.22.42:8384/


    - Scrutiny:
        icon: scrutiny
        href: http://100.69.22.42:9284
        widget:
          type: scrutiny
          url: http://100.69.22.42:9284
